name:                codewars-haskell
version:             0.1.0.0
github:              "malayantiger/codewars-haskell"
license:             BSD3
author:              "malayantiger"
copyright:           "2019 malayantiger"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/malayantiger/codewars-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck

executables:
  codewars-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars-haskell

tests:
  codewars-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars-haskell
    - hspec
    - QuickCheck
    - random
    - split
